---
driver:
  name: vagrant


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[stoffi-web::default]
  - name: web
    run_list:
      - recipe[stoffi-web::web]
    driver_config:
      network:
      - ["forwarded_port", { guest: 80, host: 8080 }]
